### PR TITLE
Add search .yaml files and exclude trash from output

### PR DESCRIPTION
**Pull request by warpreality**
Add search .yaml files and exclude trash from output

### CODE REVIEW

**Comment by yokogawa-k** [comment]
Sorry, but I do not plan to add your suggested changes to the README of this repository, as they are a bit specific.

**Comment by warpreality** [comment]
yes, but when you scan the ansible folder you need to exclude some files from the pipeline. it would be convenient if the readme already had an example of how to do this

**Comment by yokogawa-k** [comment]
Hi, thanks for your reply.

I'm interested so please let me know, why exclude "blackbox" and "compose"?
Does the latter assume "docker-compose.yaml"?

**Comment by yokogawa-k** [comment]
Hi, thanks for your reply.

I'm interested so please let me know, why exclude "blackbox" and "compose"?
Does the latter assume "docker-compose.yaml"?

**Comment by warpreality** [comment]
Yes, in my ansible repository there are some docker-compose.yaml files and blackbox configuration that are not recognized by your linter and mark as invalid accordingly. I want to tell in my MR how to exclude these files

**Comment by warpreality** [comment]
Ithese may not necessarily be docker-compose files, I just gave special cases

**Comment by yokogawa-k** [comment]
Thanks for answering so many times.

I now understand your intention in preparing this Pull Request.

I was a bit curious, so I did some research and found that for ansible-lint, there is a way to set the `exclude_path` in `ansible-lint.yml` ([doc](https://ansible-lint.readthedocs.io/en/latest/configuring/)) or the `--exclude` option on the command line.
However, [these features currently do not seem to support specifying with glob or regex](https://github.com/ansible/ansible-lint/issues/322), and I am more comfortable with `find`, which I am used to using, so I think the method you suggested is better.

I couldn't adopt it this time, but your advice was very helpful.
Thank you so much.

**Pull request closed without merging**
